# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f6f034e6b4aa8533a1ac61e0dc8a8f662b1bd441d698ab363e4bbaab3de53b793bc1a992d232e2f9b91e0701220f45725022b24363084f564dd4a464a964c52

test:
  secret_key_base: 8f3055851fc57b25d5c445e592ee0b0ae5238205f112f1ed672b49725e4c465e1035d4601691f587bb5663c7d7ef46a268ac57b010f1c665dbca6292565de9c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
